Update .install

diff --git a/.install b/.install
--- a/.install
+++ b/.install
@@ -7,16 +7,19 @@ if [ ! -d "/data/data/com.termux.api" ]; then
     exit 1
 fi
 
-arch=$(uname -m)
+source "/data/data/com.termux/files/usr/bin/termux-setup-package-manager" || { echo "Failed to load package manager"; exit 1; }
 
-if [ "$arch" = "aarch64" ]; then
-    arch="aarch64"
-elif [ "$arch" = "armv7l" ]; then
-    arch="arm"
-elif [ "$arch" = "armv8l" ]; then
-    arch="arm"
+if [ "$TERMUX_APP_PACKAGE_MANAGER" = "apt" ]; then
+    arch=$(dpkg --print-architecture)
+elif [ "$TERMUX_APP_PACKAGE_MANAGER" = "pacman" ]; then
+    arch=$(pacman-conf | awk -F ' = ' '/Architecture/ {print $2}')
 else
-    echo -e "\nArchitecture $arch not supported\n"
+    echo "Unknown package manager"
+    exit 1
+fi
+
+if [[ "$arch" != "aarch64" && "$arch" != "arm" ]]; then
+    echo "MiUnlockTool(termux) does not support architecture $arch"
     exit 1
 fi
 
